# Generated by Django 5.1.1 on 2024-09-05 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='twJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('header', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
